### ISSUE TITLE
operationTimeout and connectionTimeout functionality

### ISSUE THREAD

**Issue by sean3z** [christophermina/connect-couchbase#7]
In [`lib/connect-couchbase.js`](https://github.com/christophermina/connect-couchbase/blob/master/lib/connect-couchbase.js#L96-L102) we see `operationTimeout` and `connectionTimeout` being added to `connectionOptions` but neither are explicitly used. In fact on [`line 114`](https://github.com/christophermina/connect-couchbase/blob/master/lib/connect-couchbase.js#L114), it looks like `connectionTimeout` is defaulted to `10000` regardless of what was passed into the configuration.

I haven't been able to get either feature working as the README explains and I believe this may be the reason. Any insight would be greatly appreciated!

**Comment by christophermina** [comment]
Hi, 

The reason for this was in the updated version of Couchnode, the ability to set connection timeout was removed from the public API.  I expect they will add it back, or maybe have since added it back.  

Feel free to submit a pull request if the latter is the case, or I will look into it as soon as I can. 

Thanks.
Chris

**Comment by christophermina** [comment]
I think I put that hardcoded 10000 in there during testing and forgot to remove it.  I was testing whether or not the new couchnode API responded to setting "client.connectionTimeout = xxx".

**Comment by christophermina** [comment]
Update, I see connectionTimeout is part of the API.  I'll make sure that gets added back and I'll have NPM update published soon.  

NOte that I have removed the dependency on Couchbase from the connect-couchbase library.  It is up to the developer to ensure Couchbase 2.x is installed via NPM and is available.

**Comment by christophermina** [comment]
This has been fixed and NPM updated:  https://github.com/christophermina/connect-couchbase/commit/446ecc3f705a25fc94ab0e23a28c4aa4a5c99626
